include: package:lint/analysis_options.yaml

linter:
  rules:
    always_put_required_named_parameters_first: false
    avoid_classes_with_only_static_members: false
    sort_constructors_first: true
    lines_longer_than_80_chars: true
    curly_braces_in_flow_control_structures: false
    sort_pub_dependencies: false
    prefer_if_elements_to_conditional_expressions: false
    constant_identifier_names: false